### PR TITLE
fix: use unsigned integers in igraph_bitset_t

### LINKED ISSUE #2596: Undefined shift: `((igraph_integer_t) 1) << 63` triggers UBSan
OSS-Fuzz detects an undefined shift in the new bitset functionality. I believe the fix is to use unsigned integers.

```
/src/igraph/src/connectivity/reachability.c:108:9: runtime error: left shift of 1 by 63 places cannot be represented in type 'igraph_integer_t' (aka 'long')
	    #0 0x501abf in igraph_reachability [igraph/src/connectivity/reachability.c:108](https://github.com/igraph/igraph/blob/2b6200bc9f6271d1b68213371e56719e81f0b733/src/connectivity/reachability.c#L108):9
	    #1 0x501cda in igraph_count_reachable [igraph/src/connectivity/reachability.c:194](https://github.com/igraph/igraph/blob/2b6200bc9f6271d1b68213371e56719e81f0b733/src/connectivity/reachability.c#L194):5
	    #2 0x4c06ad in LLVMFuzzerTestOneInput [igraph/fuzzing/misc_algos.cpp:61](https://github.com/igraph/igraph/blob/2b6200bc9f6271d1b68213371e56719e81f0b733/fuzzing/misc_algos.cpp#L61):9
	    #3 0x4263d3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
	    #4 0x411b32 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
	    #5 0x4173dc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
	    #6 0x440912 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
	    #7 0x7fa934000082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/libc-start.c:308:16
	    #8 0x407cfd in _start
```

See:

 - https://oss-fuzz.com/testcase-detail/6537539805577216
 - https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68358

### PR DESCRIPTION
**Pull request by szhorvat**
Closes #2596

@Tagl, it turns out we need to use unsigned integers, otherwise UBSan complains about undefined shifts. Can you please have a look at this PR and make sure I didn't miss anything that needs to be changes to `igraph_uint_t`?

### CODE REVIEW

File: src/core/bitset.c [hunk 1]
```diff
@@ -502,8 +502,8 @@ igraph_integer_t igraph_bitset_countl_one(const igraph_bitset_t *bitset) {
 igraph_integer_t igraph_bitset_countr_zero(const igraph_bitset_t *bitset) {
     const igraph_integer_t final_block_size = bitset->size % IGRAPH_INTEGER_SIZE ? bitset->size % IGRAPH_INTEGER_SIZE : IGRAPH_INTEGER_SIZE;
     const igraph_integer_t slots = IGRAPH_BIT_NSLOTS(bitset->size);
-    const igraph_integer_t one = 1, zero = 0; /* to avoid the need to cast 1 and 0 to igraph_integer_t below */
-    const igraph_integer_t mask = final_block_size == IGRAPH_INTEGER_SIZE ? ~zero : ((one << final_block_size) - one);
+    const igraph_uint_t one = 1, zero = 0; /* to avoid the need to cast 1 and 0 to igraph_integer_t below */
```
Comment (Tagl) [inline src/core/bitset.c:505]:
```suggestion
    const igraph_uint_t one = 1, zero = 0; /* to avoid the need to cast 1 and 0 to igraph_uint_t below */
```
and in other places
